#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pygobject
Version  : 3.30.4
Release  : 29
URL      : https://download.gnome.org/sources/pygobject/3.30/pygobject-3.30.4.tar.xz
Source0  : https://download.gnome.org/sources/pygobject/3.30/pygobject-3.30.4.tar.xz
Summary  : Python bindings for GObject Introspection
Group    : Development/Tools
License  : CC-BY-SA-3.0 LGPL-2.1
Requires: pygobject-license = %{version}-%{release}
Requires: pygobject-python = %{version}-%{release}
Requires: pygobject-python3 = %{version}-%{release}
Requires: pycairo
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(pycairo)

%description
.. image:: https://pygobject.readthedocs.io/en/latest/_images/pygobject.svg
:align: center
:width: 400px
:height: 98px

%package dev
Summary: dev components for the pygobject package.
Group: Development
Provides: pygobject-devel = %{version}-%{release}

%description dev
dev components for the pygobject package.


%package license
Summary: license components for the pygobject package.
Group: Default

%description license
license components for the pygobject package.


%package python
Summary: python components for the pygobject package.
Group: Default
Requires: pygobject-python3 = %{version}-%{release}

%description python
python components for the pygobject package.


%package python3
Summary: python3 components for the pygobject package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pygobject package.


%prep
%setup -q -n pygobject-3.30.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543767802
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/pygobject
cp COPYING %{buildroot}/usr/share/package-licenses/pygobject/COPYING
cp docs/images/LICENSE %{buildroot}/usr/share/package-licenses/pygobject/docs_images_LICENSE
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pygobject-3.0/pygobject.h
/usr/lib64/pkgconfig/pygobject-3.0.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pygobject/COPYING
/usr/share/package-licenses/pygobject/docs_images_LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
