#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pygobject
Version  : 3.26.1
Release  : 7
URL      : https://download.gnome.org/sources/pygobject/3.26/pygobject-3.26.1.tar.xz
Source0  : https://download.gnome.org/sources/pygobject/3.26/pygobject-3.26.1.tar.xz
Summary  : Python bindings for GObject
Group    : Development/Tools
License  : LGPL-2.1
Requires: pygobject-python3
Requires: pygobject-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-gobject)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(libffi)
BuildRequires : py2cairo
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
PyGObject
=====
Original authors:   James Henstridge <james@daa.com.au>
Johan Dahlin <johan@gnome.org>

%package dev
Summary: dev components for the pygobject package.
Group: Development
Provides: pygobject-devel

%description dev
dev components for the pygobject package.


%package python
Summary: python components for the pygobject package.
Group: Default
Requires: pygobject-python3

%description python
python components for the pygobject package.


%package python3
Summary: python3 components for the pygobject package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pygobject package.


%prep
%setup -q -n pygobject-3.26.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1509104350
%configure --disable-static --disable-cairo
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1509104350
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pygobject-3.0/pygobject.h
/usr/lib64/pkgconfig/pygobject-3.0.pc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
